spring:
  datasource:
    url: jdbc:postgresql://localhost:1502/${AUTH_DB_NAME}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
